# This file was generated by GoReleaser. DO NOT EDIT.
cask "llm-mux" do
  name "llm-mux"
  desc "Multi-provider LLM gateway with unified API"
  homepage "https://github.com/nghyane/llm-mux"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llm-mux"

  on_macos do
    on_intel do
      url "https://github.com/nghyane/llm-mux/releases/download/v#{version}/llm-mux_#{version}_darwin_amd64.tar.gz"
      sha256 "bb296cfb28f2bb8bbb362328f32ef2576d7038409bdace8fbd82fbae541d9e38"
    end
    on_arm do
      url "https://github.com/nghyane/llm-mux/releases/download/v#{version}/llm-mux_#{version}_darwin_arm64.tar.gz"
      sha256 "254a3887a34fa87af0531fabbcf2678d098086d73230604da75f83cd521e11ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nghyane/llm-mux/releases/download/v#{version}/llm-mux_#{version}_linux_amd64.tar.gz"
      sha256 "f88002af6b237104097df83274dcda214500234a22502b8173165de5cfb30488"
    end
    on_arm do
      url "https://github.com/nghyane/llm-mux/releases/download/v#{version}/llm-mux_#{version}_linux_arm64.tar.gz"
      sha256 "1ad2d72a7cebffaea3a1db578abe38f663997155d44e3ea10d5ac1d8e5e0f5db"
    end
  end

  caveats do
    "Initialize config with: llm-mux --init"
    "Then start server with: llm-mux"
  end

  # No zap stanza required
end
