# This file was generated by GoReleaser. DO NOT EDIT.
cask "llm-mux" do
  name "llm-mux"
  desc "Multi-provider LLM gateway with unified API"
  homepage "https://github.com/nghyane/llm-mux"
  version "1.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "llm-mux"

  on_macos do
    on_intel do
      url "https://github.com/nghyane/llm-mux/releases/download/v#{version}/llm-mux_#{version}_darwin_amd64.tar.gz"
      sha256 "986e8d7232ca8e6d740a0bf85c82b525a744c6f58bb4cc0f64ff4a5f26b7f972"
    end
    on_arm do
      url "https://github.com/nghyane/llm-mux/releases/download/v#{version}/llm-mux_#{version}_darwin_arm64.tar.gz"
      sha256 "99626a9d04da6de3fe4c2fcf17c4dac98eb06eb02638bb49346e58136e70170d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/nghyane/llm-mux/releases/download/v#{version}/llm-mux_#{version}_linux_amd64.tar.gz"
      sha256 "0f5c6285d81ef55b7aa52f1d7b5bd63547493a9bf1ea190abe0fbcf3ab8170d6"
    end
    on_arm do
      url "https://github.com/nghyane/llm-mux/releases/download/v#{version}/llm-mux_#{version}_linux_arm64.tar.gz"
      sha256 "ee5174d968f03a6b9b958cfc40cc02fb96c398cf8d193ca7b1a2039ef017f568"
    end
  end

  caveats do
    "Initialize config with: llm-mux --init"
    "Then start server with: llm-mux"
  end

  # No zap stanza required
end
