# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmMux < Formula
  desc "Multi-provider LLM gateway with unified API"
  homepage "https://github.com/nghyane/llm-mux"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nghyane/llm-mux/releases/download/v1.0.0/llm-mux_1.0.0_darwin_amd64.tar.gz"
      sha256 "790b8ad7bcaf9fdd60732a6b913b52e1dfb57f132ba635bd8a65db878e56f19c"

      def install
        bin.install "llm-mux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nghyane/llm-mux/releases/download/v1.0.0/llm-mux_1.0.0_darwin_arm64.tar.gz"
      sha256 "71f61d36b04b361661060b298ca189407d3870167e40788eacbf15c7db18666c"

      def install
        bin.install "llm-mux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nghyane/llm-mux/releases/download/v1.0.0/llm-mux_1.0.0_linux_amd64.tar.gz"
      sha256 "bee397eadca723062bf464cc5b1d641a81a94a9c0b91670ea0de4dac95f2cd8f"
      def install
        bin.install "llm-mux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nghyane/llm-mux/releases/download/v1.0.0/llm-mux_1.0.0_linux_arm64.tar.gz"
      sha256 "fea4c011162aca09a62b678c13d6a848cfbeff466da87ba4ff2164eace08eef1"
      def install
        bin.install "llm-mux"
      end
    end
  end

  def post_install
    (etc/"llm-mux").mkpath
    (var/"llm-mux").mkpath
    etc.install "config.example.yaml" => "llm-mux/config.yaml" unless (etc/"llm-mux/config.yaml").exist?
  end

  def caveats
    <<~EOS
      Config file: #{etc}/llm-mux/config.yaml

      To start llm-mux:
        brew services start llm-mux

      Or run manually:
        llm-mux -config #{etc}/llm-mux/config.yaml
    EOS
  end

  service do
    run [opt_bin/"llm-mux", "-config", etc/"llm-mux/config.yaml"]
    keep_alive true
    log_path var/"log/llm-mux.log"
    error_log_path var/"log/llm-mux.log"
    working_dir var/"llm-mux"
  end

  test do
    system "#{bin}/llm-mux", "-version"
  end
end
