# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmMux < Formula
  desc "Multi-provider LLM gateway with unified API"
  homepage "https://github.com/nghyane/llm-mux"
  version "6.5.31"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nghyane/llm-mux/releases/download/v6.5.31/llm-mux_6.5.31_darwin_amd64.tar.gz"
      sha256 "dcea588dbcb4fb0d8d00a3bd6021a50c422d73e9691294c9f2eab80aaff6cfca"

      def install
        bin.install "llm-mux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nghyane/llm-mux/releases/download/v6.5.31/llm-mux_6.5.31_darwin_arm64.tar.gz"
      sha256 "93dc9976abaa89f5e8dc11784838ffb7be68906195245dfbd60954c1e641de5b"

      def install
        bin.install "llm-mux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nghyane/llm-mux/releases/download/v6.5.31/llm-mux_6.5.31_linux_amd64.tar.gz"
      sha256 "2214e005cce70e9f31b3b0c1a0d42d68573eb8a98a85b0e8cc1bc3f6e5c3a08f"
      def install
        bin.install "llm-mux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nghyane/llm-mux/releases/download/v6.5.31/llm-mux_6.5.31_linux_arm64.tar.gz"
      sha256 "4d4de6eeb8227a91c5e4a04254331f986553245bf2841b47c443d57253eb674b"
      def install
        bin.install "llm-mux"
      end
    end
  end

  def post_install
    (etc/"llm-mux").mkpath
    (var/"llm-mux").mkpath
    etc.install "config.example.yaml" => "llm-mux/config.yaml" unless (etc/"llm-mux/config.yaml").exist?
  end

  def caveats
    <<~EOS
      Config file: #{etc}/llm-mux/config.yaml

      To start llm-mux:
        brew services start llm-mux

      Or run manually:
        llm-mux -config #{etc}/llm-mux/config.yaml
    EOS
  end

  service do
    run [opt_bin/"llm-mux", "-config", etc/"llm-mux/config.yaml"]
    keep_alive true
    log_path var/"log/llm-mux.log"
    error_log_path var/"log/llm-mux.log"
    working_dir var/"llm-mux"
  end

  test do
    system "#{bin}/llm-mux", "-version"
  end
end
