# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmMux < Formula
  desc "Multi-provider LLM gateway with unified API"
  homepage "https://github.com/nghyane/llm-mux"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nghyane/llm-mux/releases/download/v1.0.0/llm-mux_1.0.0_darwin_amd64.tar.gz"
      sha256 "fa8db3f04198cb620145efcc2c15f099cd6a42dc712bb8954b20713ce5692cd8"

      def install
        bin.install "llm-mux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nghyane/llm-mux/releases/download/v1.0.0/llm-mux_1.0.0_darwin_arm64.tar.gz"
      sha256 "7992449950c9487d0f1b600aeba2d707f7c608414b487f721911840ce0f653ed"

      def install
        bin.install "llm-mux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nghyane/llm-mux/releases/download/v1.0.0/llm-mux_1.0.0_linux_amd64.tar.gz"
      sha256 "8a517ac1c25bb025caa9b1d1f2808c35a76b65ca32f55d174a7a2898382b5d7b"
      def install
        bin.install "llm-mux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nghyane/llm-mux/releases/download/v1.0.0/llm-mux_1.0.0_linux_arm64.tar.gz"
      sha256 "b73b5b8b92e3b9d59bc641433fd10f33b3641a711a91bbd81a51b271110ddbe4"
      def install
        bin.install "llm-mux"
      end
    end
  end

  def post_install
    (etc/"llm-mux").mkpath
    (var/"llm-mux").mkpath
    etc.install "config.example.yaml" => "llm-mux/config.yaml" unless (etc/"llm-mux/config.yaml").exist?
  end

  def caveats
    <<~EOS
      Config file: #{etc}/llm-mux/config.yaml

      To start llm-mux:
        brew services start llm-mux

      Or run manually:
        llm-mux -config #{etc}/llm-mux/config.yaml
    EOS
  end

  service do
    run [opt_bin/"llm-mux", "-config", etc/"llm-mux/config.yaml"]
    keep_alive true
    log_path var/"log/llm-mux.log"
    error_log_path var/"log/llm-mux.log"
    working_dir var/"llm-mux"
  end

  test do
    system "#{bin}/llm-mux", "-version"
  end
end
